/**/floor_detection:
  ros__parameters:
    input_topic: "cloud_filtered"
    base_frame: "base_footprint"
    
    # Passthrough Filter
    floor_height_min: -2.0
    floor_height_max: 0.5
    plane_dist_threshold: 0.05

    # Clustering
    cluster_tolerance: 0.05
    min_cluster_size: 100
    max_cluster_size: 10000

    # RANSAC Parameters
    ransac_max_iterations: 100
    
    # Vertical Structure Filter
    use_vertical_filter: true
    vertical_slice_thickness: 0.02
    vertical_xy_cell_size: 0.03
    vertical_required_continuity: 0.15
    vertical_min_pts_per_cell: 3
    
    # Object Size Filters
    object_size_x_min: 0.05
    object_size_x_max: 0.80
    object_size_y_min: 0.05
    object_size_y_max: 0.80
    object_size_z_min: 0.05
    object_size_z_max: 0.80
