/**/line_detection:
  ros__parameters:
    input_topic: "/scan"
    odom_frame: "odom"
    base_frame: "base_footprint"

    # Passthrough Filter
    passthrough_axis: "y"
    passthrough_min: -1.0
    passthrough_max: 1.0
    distance_threshold: 0.01
    probability: 0.95

    # RANSAC Parameters
    ransac_max_iterations: 100
