line_detection:
  ros__parameters:
    input_topic: "cloud_filtered"
    base_frame: "D435i/camera/_depth_frame"

    # Passthrough Filter
    passthrough_axis: "y"
    passthrough_min: -1.5
    passthrough_max: 1.5
    distance_threshold: 0.02
    probability: 0.95

    # RANSAC Parameters
    ransac_max_iterations: 100
