/**/preprocessor:
  ros__parameters:
    input_topic: "cloud_raw"
    output_topic: "cloud_filtered"
    base_frame: "base_footprint"

    # Passthrough Filter
    voxel_leaf_size: 0.03
    x_min: 0.2
    x_max: 1.0
    y_min: -2.0
    y_max: 2.0
    z_min: -2.0
    z_max: 2.0
