pcl_line_detection:
  ros__parameters:
    scan_topic_name : /scan
    base_frame_name : base_footprint

    passthrough_y_min : -1.0
    passthrough_y_max : 1.0

    threshold_distance : 0.01
    probability : 0.95

    need_marker : true
    need_cloud_line : true
    need_line_info : true