pcl_object_detection/pcl_object_detection:
  ros__parameters:
    floor: 
      passthrough_x_min : 0.3
      passthrough_x_max : 1.5
      passthrough_y_min : -0.7
      passthrough_y_max : 0.7
      passthrough_z_min : -0.3
      passthrough_z_max : 1.0
